name: test

on:
  [push, pull_request]

jobs:
  test-dotnet:
    name: test dotnet
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Set environment variables
        run: |
            echo "DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true" >> $GITHUB_ENV
            echo "DOTNET_CLI_TELEMETRY_OPTOUT=true" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: '7.0.x'
        
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Debug --no-restore
       
      - name: Test
        run: dotnet test -c Debug --no-restore --logger "trx;LogFileName=test-results.trx"
        
      - name: Report Results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Results
          path: ./**/*.trx
          reporter: dotnet-trx